'use client';
import { useState } from 'react';
import { ArrowDown,ArrowRight,Check,ChevronLeft,ChevronRight,Cloud,Code2,Database,Globe2,HardDrive,Layers3,Network,Play,Server,ShieldCheck,Zap } from 'lucide-react';

const products=[
{icon:Server,name:'Droplets',kind:'Cómputo',short:'Máquinas virtuales Linux sobre hardware virtualizado.',detail:'Eliges imagen, CPU, memoria y región. Obtienes un servidor con dirección IP para instalar y administrar tu software.',control:'Más control',use:'APIs, servidores web y cargas personalizadas.'},
{icon:Code2,name:'App Platform',kind:'PaaS',short:'Despliegue desde un repositorio sin administrar servidores.',detail:'Conectas el código, la plataforma detecta cómo construirlo, crea los componentes y publica la aplicación con HTTPS.',control:'Menos operación',use:'Web apps, APIs y entrega continua.'},
{icon:Layers3,name:'Kubernetes',kind:'Orquestación',short:'Clústeres con plano de control administrado.',detail:'DigitalOcean administra el control plane; tú despliegas contenedores y defines cómo escalan, se conectan y recuperan.',control:'Escala avanzada',use:'Microservicios y plataformas distribuidas.'},
{icon:Database,name:'Managed Databases',kind:'Datos',short:'Motores de datos operados como servicio.',detail:'La plataforma se ocupa de tareas operativas del clúster para que la aplicación consuma la base de datos como un servicio.',control:'Datos gestionados',use:'Persistencia sin operar el motor directamente.'},
{icon:HardDrive,name:'Spaces',kind:'Objetos',short:'Almacenamiento de archivos y contenido estático.',detail:'Guarda objetos fuera del servidor de la aplicación para separar el cómputo de los archivos que deben persistir.',control:'Escala de objetos',use:'Imágenes, copias y contenido distribuible.'},
{icon:Network,name:'Networking',kind:'Conectividad',short:'VPC, balanceadores, firewalls y DNS.',detail:'Conecta servicios de forma privada, controla el tráfico permitido y distribuye solicitudes entre varias instancias.',control:'Tráfico seguro',use:'Arquitecturas resilientes y servicios privados.'}];
const deploySteps=[
{n:'01',title:'Código',kicker:'Repositorio',text:'El equipo envía un cambio a Git. Ese commit se convierte en la fuente del despliegue.',icon:Code2},
{n:'02',title:'Construcción',kicker:'Build',text:'La plataforma instala dependencias y genera el artefacto que ejecutará la aplicación.',icon:Layers3},
{n:'03',title:'Infraestructura',kicker:'Provisioning',text:'Se prepara el servicio: App Platform, un Droplet o un clúster Kubernetes.',icon:Server},
{n:'04',title:'Red',kicker:'Routing',text:'DNS, HTTPS y el balanceador dirigen el tráfico hacia instancias saludables.',icon:Network},
{n:'05',title:'Producción',kicker:'Live',text:'La nueva versión recibe peticiones; métricas y alertas ayudan a observar su estado.',icon:Globe2}];
const requestSteps=[
{label:'Usuario',sub:'Solicita app.midominio.com',color:'cyan',icon:Globe2},
{label:'DNS + HTTPS',sub:'Resuelve y protege',color:'blue',icon:ShieldCheck},
{label:'Load Balancer',sub:'Elige una instancia saludable',color:'violet',icon:Network},
{label:'Aplicación',sub:'Procesa la solicitud',color:'green',icon:Server},
{label:'Base de datos',sub:'Lee o guarda información',color:'amber',icon:Database}];

export default function Home(){
const [product,setProduct]=useState(0),[deploy,setDeploy]=useState(0),[request,setRequest]=useState(0);const active=products[product],ProductIcon=active.icon,RequestIcon=requestSteps[request].icon;
return <main>
<nav className="site-nav"><a className="wordmark" href="#inicio"><span>DO</span> DigitalOcean / Explainer</a><div className="nav-links"><a href="#mapa">Plataforma</a><a href="#despliegue">Despliegue</a><a href="#peticion">Petición</a></div><div className="live-dot"><i/> MODO EXPOSICIÓN</div></nav>
<section className="hero" id="inicio"><div className="hero-copy"><p className="overline">Cloud computing, explicado visualmente</p><h1>De código<br/>a <em>la nube.</em></h1><p className="hero-lead">DigitalOcean ofrece infraestructura y servicios administrados para construir, desplegar y escalar aplicaciones sin poseer un centro de datos.</p><div className="hero-actions"><a className="button primary" href="#mapa"><Play size={17} fill="currentColor"/> Comenzar recorrido</a><a className="button secondary" href="#despliegue">Ver el step by step <ArrowDown size={17}/></a></div></div><div className="cloud-scene" aria-label="Diagrama de una aplicación en la nube"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="cloud-core"><Cloud size={62}/><b>DIGITAL<br/>OCEAN</b></div><div className="float-node node-one"><Code2/><span>Tu código</span></div><div className="float-node node-two"><Server/><span>Cómputo</span></div><div className="float-node node-three"><Database/><span>Datos</span></div><div className="float-node node-four"><Globe2/><span>Usuarios</span></div></div></section>
<section className="dark-section" id="mapa"><div className="section-heading"><div><p className="overline blue">01 / LA PLATAFORMA</p><h2>Un océano de<br/>bloques simples.</h2></div><p>La nube se entiende como un conjunto de piezas. Elige una para explicar qué responsabilidad asume y cuándo se utiliza.</p></div><div className="product-explorer"><div className="product-grid" role="tablist" aria-label="Productos de DigitalOcean">{products.map((item,i)=>{const Icon=item.icon;return <button key={item.name} role="tab" aria-selected={product===i} className={`product-tab ${product===i?'active':''}`} onClick={()=>setProduct(i)}><Icon/><span><small>{item.kind}</small><strong>{item.name}</strong></span><ArrowRight className="arrow"/></button>})}</div><div className="product-detail" role="tabpanel"><div className="detail-index">0{product+1} / 06</div><ProductIcon className="detail-icon"/><p className="detail-kind">{active.kind}</p><h3>{active.name}</h3><p className="detail-lead">{active.short}</p><p className="detail-copy">{active.detail}</p><div className="detail-meta"><div><small>ENFOQUE</small><b>{active.control}</b></div><div><small>IDEAL PARA</small><b>{active.use}</b></div></div></div></div></section>
<section className="deploy-section" id="despliegue"><div className="section-heading light"><div><p className="overline">02 / STEP BY STEP</p><h2>Así llega una app<br/>a producción.</h2></div><p>Avanza por cinco etapas. El recorrido mantiene visible la relación entre código, infraestructura y red.</p></div><div className="deploy-stage"><div className="deploy-track">{deploySteps.map((item,i)=>{const Icon=item.icon;return <button key={item.n} onClick={()=>setDeploy(i)} className={`deploy-node ${i<deploy?'done':''} ${i===deploy?'active':''}`} aria-label={`Paso ${i+1}: ${item.title}`}><span className="node-circle">{i<deploy?<Check/>:<Icon/>}</span><b>{item.title}</b><small>{item.kicker}</small></button>})}<div className="track-line"><span style={{width:`${deploy*25}%`}}/></div></div><div className="deploy-card" aria-live="polite"><div className="giant-number">{deploySteps[deploy].n}</div><div><p className="overline">{deploySteps[deploy].kicker}</p><h3>{deploySteps[deploy].title}</h3><p>{deploySteps[deploy].text}</p></div></div><div className="step-controls"><button className="button secondary" disabled={deploy===0} onClick={()=>setDeploy(Math.max(0,deploy-1))}><ChevronLeft/> Anterior</button><span>{deploy+1} de {deploySteps.length}</span><button className="button primary" onClick={()=>setDeploy(deploy===4?0:deploy+1)}>{deploy===4?'Reiniciar':'Siguiente'} <ChevronRight/></button></div></div></section>
<section className="request-section" id="peticion"><div className="section-heading"><div><p className="overline blue">03 / CÓMO FUNCIONA</p><h2>El viaje de<br/>una petición.</h2></div><p>Cada clic avanza la solicitud por una arquitectura típica. Los servicios pueden variar, pero la separación de responsabilidades permanece.</p></div><div className="request-lab"><div className="request-visual">{requestSteps.map((item,i)=>{const Icon=item.icon;return <div key={item.label} className={`request-node ${i===request?'active':''} ${i<request?'passed':''}`}><div className={item.color}><Icon/></div><span>{item.label}</span>{i<requestSteps.length-1&&<ArrowRight className="request-arrow"/>}</div>})}</div><div className="request-console"><div className="console-top"><span/><span/><span/><b>request.trace</b></div><div className="console-body"><p><i>$</i> trace app.midominio.com</p><p className="muted">paso {String(request+1).padStart(2,'0')} / 05</p><div className="console-result"><RequestIcon/><div><small>AHORA EN</small><strong>{requestSteps[request].label}</strong><p>{requestSteps[request].sub}</p></div></div><p className="status"><Zap/> estado: procesando correctamente</p></div><div className="console-actions"><button onClick={()=>setRequest(request===0?4:request-1)}><ChevronLeft/> Retroceder</button><button onClick={()=>setRequest(request===4?0:request+1)}>Avanzar <ChevronRight/></button></div></div></div></section>
<section className="summary-section"><p className="overline">04 / PARA RECORDAR</p><h2>La idea no es tener servidores.<br/><em>Es entregar software.</em></h2><div className="summary-grid"><article><b>01</b><h3>Abstracción</h3><p>Elige cuánto quieres administrar: desde una VM hasta una plataforma que despliega por ti.</p></article><article><b>02</b><h3>Composición</h3><p>Cómputo, datos, almacenamiento y red se conectan para formar una arquitectura.</p></article><article><b>03</b><h3>Escala</h3><p>Se agregan instancias y balanceo para repartir carga y evitar un único punto de fallo.</p></article></div><div className="sources"><span>Fuentes oficiales:</span><a href="https://docs.digitalocean.com/products/droplets/getting-started/" target="_blank" rel="noreferrer">Droplets</a><a href="https://docs.digitalocean.com/products/app-platform/" target="_blank" rel="noreferrer">App Platform</a><a href="https://docs.digitalocean.com/products/kubernetes/getting-started/" target="_blank" rel="noreferrer">Kubernetes</a></div></section>
<footer><div className="wordmark"><span>DO</span> DigitalOcean / Explainer</div><p>Una guía visual para comprender la nube.</p><a href="#inicio">Volver arriba ↑</a></footer>
</main>}
